export const codeToFull = [
    { value: 'en', label: 'English' },
    { value: 'zh', label: 'Mandarin Chinese' },
    { value: 'hi', label: 'Hindi' },
    { value: 'es', label: 'Spanish' },
    { value: 'fr', label: 'French' },
    { value: 'ar', label: 'Arabic' },
    { value: 'bn', label: 'Bengali' },
    { value: 'ru', label: 'Russian' },
    { value: 'pt', label: 'Portuguese' },
    { value: 'id', label: 'Indonesian' },
    { value: 'ur', label: 'Urdu' },
    { value: 'de', label: 'German' },
    { value: 'ja', label: 'Japanese' },
    { value: 'sw', label: 'Swahili' },
    { value: 'it', label: 'Italian' },
    { value: 'pa', label: 'Punjabi' },
];

export const fullToCode = {
    English: 'en',
    Spanish: 'es',
    Hindi: 'hi',
    'Mandarin Chinese': 'zh',
    French: 'fr',
    Arabic: 'ar',
    Bengali: 'bn',
    Russian: 'ru',
    Portuguese: 'pt',
    Indonesian: 'id',
    Urdu: 'ur',
    German: 'de',
    Japanese: 'ja',
    Swahili: 'sw',
    Italian: 'it',
    Punjabi: 'pa',
};